### ISSUE TITLE
WebPG Icon Not Showing in Git Version

### ISSUE THREAD

**Issue by willysr** [kylehuff/webpg-firefox#10]
When building from GIT, the WebPG icon not showing up in both old and new interface

first two screenshots are taken using binary packages
![binary-new-interface](https://f.cloud.github.com/assets/240100/463869/ab578958-b5a9-11e2-92a8-4abb8207c77d.jpg)
![binary-old-interface](https://f.cloud.github.com/assets/240100/463870/abe7029a-b5a9-11e2-8e66-4979fcecbaf4.jpg)

next two screenshots are taken when using git version
![git-new-interface](https://f.cloud.github.com/assets/240100/463872/be240f2a-b5a9-11e2-982d-8fe6e3611155.jpg)
![git-old-interface](https://f.cloud.github.com/assets/240100/463873/be265280-b5a9-11e2-80eb-769fa4e7b2ef.jpg)

**Comment by kylehuff** [comment]
Is the GMAIL integration option enabled in the WebPG options?

If yes, then did you reload GMAIL after enabling? (no listeners to create the button are present on the page unless GMAIl integration was enabled when the page loaded)

**Comment by willysr** [comment]
> Is the GMAIL integration option enabled in the WebPG options?

Yes, i have set it to Enabled

> If yes, then did you reload GMAIL after enabling? (no listeners to create the button are present on the page unless GMAIl integration was enabled when the page loaded)

The browser needs to be restarted after installing the new version of
the extension, so yes, it has been reloaded

## 

Willy Sudiarto Raharjo

**Comment by willysr** [comment]
Thanks
by the way, this WebPG icon is also showing up in the github comment form :)

**Comment by kylehuff** [comment]
Are you referring to the toolbar with the secure secure editor, sign, encrypt buttons etc?

If the textarea toolbar is enabled in the options for inline formatting, the toolbar will be present on any textarea or content-editable field of at least a certain size, unless otherwise black-listed.

**Comment by willysr** [comment]
> Are you referring to the toolbar with the secure secure editor, sign, encrypt buttons etc?

Yes

> If the textarea toolbar is enabled in the options for inline formatting, the toolbar will be present on any textarea or content-editable field of at least a certain size, unless otherwise black-listed.

so i guess that is the culprit of the high CPU usage since it will try
to find any textarea on every opened page

## 

Willy Sudiarto Raharjo

**Comment by kylehuff** [comment]
Yes and no. If you disable the toolbar feature, you probably won't see much a difference in CPU usage (slight, but probably not much).

Most of the CPU usage is from Mozilla's implementation of the MutationObersver and TreeWalker, which is very slow compared to the webkit implementations. I have been working on narrowing down the scope of elements that get observed and/or walked, but that is still a work in progress.

**Comment by willysr** [comment]
> Yes and no. If you disable the toolbar feature, you probably won't see much a difference in CPU usage (slight, but probably not much).
> 
> Most of the CPU usage is from Mozilla's implementation of the MutationObersver and TreeWalker, which is very slow compared to the webkit implementations. I have been working on narrowing down the scope of elements that get observed and/or walked, but that is still a work in progress.

OK, i will just wait and see for future improvements while doing more testing

Thanks Kyle :)

## 

Willy Sudiarto Raharjo
