### ISSUE TITLE
webpg-toolbar position when inside a position:relative

### ISSUE THREAD

**Issue by puggan** [kylehuff/webpg-firefox#17]
"webpg-toolbar" uses postion absolue tp position it self inside the textarea, but it assumes there is no position:relative, and uses a postion relative to the window.

Exemple:
&lt;html>
&lt;body>
&lt;div style='position: relative; margin-left: 400px;'>
&lt;textarea style='width: 200px; height: 200px'>
&lt;/textarea>
&lt;/div>
&lt;/body>
&lt;/html>

"webpg-toolbar" ends up at 520px left of the div, and that 320px outside of the textarea.

**Comment by puggan** [comment]
same problem if the div is position: fixed, or absolute

**Comment by kylehuff** [comment]
This should be fixed with the most recent commit.

Thanks for reporting this!
