### ISSUE TITLE
Webpg made firefox crash

### ISSUE THREAD

**Issue by NgoHuy** [kylehuff/webpg-firefox#19]
Hi you,
I use webpg on firefox 27,0,0-1, Archlinux

I got segmentation fault with dirmngr, but when I tested with gnupg, everything worked fine. Only removing webpg addon, my browser worked fine

Please fix this bug :-)

**Comment by kylehuff** [comment]
What version of WebPG was this segfault with? Also what architecture? 64 or 32bit?
