### ISSUE TITLE
GUI and translations

### ISSUE THREAD

**Issue by lukasz-pawlowski** [kylehuff/webpg-firefox#3]
I've translated locales/en-US to locales/pl-PL.
Not whole GUI is managed through XUL and DTD files. I recommend to rewrite GUI, so adding later translations and maintaining GUI is easier. I know it is not a one-day work. But I think it's needed.
I know, I know, this GUI is cool, has funky colours etc. But please consider above. First of all, it should be functional, not beautiful (and I think that it should be also as transparent, as possible).

PS. Sorry, if you want, move it to chrome-extension.

**Comment by kylehuff** [comment]
Yes, you are right, most of the GUI is not handled through XUL and DTD files.

As for XUL, as little as humanly possible is handled via XUL, as it is a cumbersome, hideous and entirely product specific format. No part of the working GUI actually is rendered via XUL. The XUL is primarily just a wrapper to house the HTML/JavaScript.

Also yes, it should be functional, and I have translation at the top of my TODO list. (in addition to that, tools for translators to submit translated strings is also at the top of my list).

This item has been added to the roadmap @ webpg.org for some time now, but I just created a corresponding issue on the webpg-chrome issues page (kylehuff/webpg-chrome#67).

**Comment by kylehuff** [comment]
Most of the interface has been reworked to use i18n.

The tool currently being used to allow users to submit translations is described here: http://webpg.org/?view=contribute#translate

Work continues to move the remaining pieces of the interface to translatable strings.
