### ISSUE TITLE
Several major problems on linux

### ISSUE THREAD

**Issue by giacmir** [kylehuff/webpg-firefox#4]
I'm using Debian Unstable with Firefox downloaded from Mozilla (latest version).
- After firefox relaunch to complete installation (and successive launches) 70 windows spawn saying "can't load webpg"
- Can't save any setting
- Rebuild key list is stuck and nothing happens

**Comment by kylehuff** [comment]
This sounds like a problem with the XUL declarations for the NPAPI plugin, although, I don't know how/why at the moment.

Can you confirm the version of webpg-firefox you are using?

**Comment by giacmir** [comment]
I installed version 0.8.8 from firefox extensions internal search.

**Comment by darkpixel** [comment]
What version of firefox are you using?

**Comment by darkpixel** [comment]
I just tested under Firefox 16.0.1 under Ubuntu 12.04 without problems.  I was able to generate a new key, enable it, and check my own (very outdated) key at http://darkpixel.com/pgp/

**Comment by giacmir** [comment]
I'm using Firefox 16.0.1 64bit downloaded from official mozilla page under a fully updated Debian unstable running KDE 4.8.4

**Comment by darkpixel** [comment]
I tested using this release here:
http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/16.0.1/linux-x86_64/en-US/firefox-16.0.1.tar.bz2

It worked for me, but I'm running Ubuntu 12.04 and not Debian.

Are you sure you have the required libraries installed:
http://www.curetheitch.com/projects/webpg-firefox/3/

gpg, gnupg2 and a working key agent?

The Debian/Ubuntu packages names are probably the same.  Here's what I have installed (not sure if they are all required):  apt-get install gnupg2 gpgv libgpg-error-dev libgpg-error0 libgpgme11 libgpgme11-dev

**Comment by kylehuff** [comment]
Just to note, none of the following should be required for operation of WebPG `libgpg-error-dev libgpg-error0 libgpgme11 libgpgme11-dev`

libgpgme and libgpg-error are statically linked, and do not need to be installed on the host.

**Comment by giacmir** [comment]
I have all the required libraries installed and updated. 
I've tried to install the extension in chromium and got different issues, but the extension didn't work there either. So it is probable that there is something in my environment not set up properly.

After some research I found out that the use-agent configuration key was turned off, after turning it on I had some troubles solved in chromium (but decryption continues to fail) but no progress at all in Firefox, especially the 70 error windows are really annoying.

Post here the issues in chromium as they can be useful to cross-identify the problem
- can't view private or public keys (solved after enabling agent)
- decrypt command on a signed text does nothing (after enabling agent there is a message like "can't decrypt message, copy to clipboard")
- can't save preferences (solved after enabling agent)

Issues in Firefox are the same as before and nothing changed after use agent configuration change

Thanks for the attention.

**Comment by darkpixel** [comment]
Are you able to decrypt signed data normally?
What happens if you copy some signed data, go into the terminal, and type 'gpg --verify', hit enter, paste the data in, hit enter, then hit CTRL+D?

(Or to test decryption, copy encrypted data and use 'gpg --decrypt')

**Comment by giacmir** [comment]
There are no problems doing gpg operations from command line or by using other software like "kgpg" or the "enigmail" extension for thunderbird.

**Comment by kylehuff** [comment]
I know it is a pain to start up firefox with the present issue(s), but I would be interested in seeing the output of firefox run via the console, with the following work-flow -

1.) Run firefox without WebPG installed via the console
2.) Install WebPG, and choose "restart now"
3.) Collect the output of the install process on the console (I expect there should be at least _something_)

**Comment by giacmir** [comment]
Using the console there is an interesting message:

```
LoadPlugin: failed to initialize shared library /home/giacomo/.mozilla/firefox/7qm7axkm.default/extensions/webpg-firefox@curetheitch.com/plugins/npwebpg-extonly-v0.6.1-Linux_x86-gcc3.so [/home/giacomo/.mozilla/firefox/7qm7axkm.default/extensions/webpg-firefox@curetheitch.com/plugins/npwebpg-extonly-v0.6.1-Linux_x86-gcc3.so: wrong ELF class: ELFCLASS32]
```

It seems that the plugin tries to use 32bit libraries instead of 64bit

I tried building the github version and instead of 70 windows I only get 3 (and not even always) and in the config page there are these error messages:
- There is a problem with your configuration
- There was a problem loading the plugin; the plugin might be incompatibly compiled for this architechture

**Comment by kylehuff** [comment]
That is not an error per-se, that is just Firefox attempting to load all of the ELF binaries, including the 32bit version which obviously will not work. The absence of any output referencing the 64bit version (npwebpg-extonly-v0.6.1-Linux_x86_64-gcc3.so) means that it more than likely is loading correctly.

Would it be possible for you to try the Google Chrome/Chromium version of WebPG? It is much easier to obtain the status of the bundled plugin within chrome, due the console tools it provides.

If you are willing, just install webpg-chrome via the chrome webstore at the link referenced below, and if you don't get any errors on installation of the extension, follow the steps below.

1.) Open Settings
2.) Click on the "Extensions" link on the left navigation column
3.) Click on the check-box "Developer mode" at the top right (top left if using RTL locale)
4.) Click on the link "_generated_background_page.html" in the "Inspect views:" line
5.) Note any errors within the view console, then type: `plugin.webpg_status` and press enter
6.) Expand the various elements returned from the status object, and copy/paste them back to me.

This might give us some better idea of what exactly is going on.

Here is the link to the webpg-chrome extension: https://chrome.google.com/webstore/detail/webpg/hhaopbphlojhnmbomffjcbnllcenbnih

As to why the version you compiled would not initialize, I do not know, it more than likely has to do with your build environment (i.e. it is possible your version of LIBC or some other needed library is not compatible with the version of libgpgme shipped with the source-code that the plugin links to. just a guess).

Thanks for all your help trying to track this issue down, I think we are getting close to identifying the cause of the problem.

**Comment by giacmir** [comment]
I tried the extension in Chromium (version 22.0.1229.94 Debian wheezy/sid) following your instructions. 

During the installation and looking at the console there are no errors. And in the configuration page I have only green checks. 

```
Your system appears to be configured correctly, you should be able to use WebPG!
The WebPG NPAPI Plugin is valid; version 0.6.1
It appears you have a working version of libgpgme; version 1.3.2
It appears you have a key-agent configured
gpgconf was detected; you can use the signature methods
```

Console output: 

```
my plugin returned: true; version 0.6.1
background initted 
```

But if I try to decrypt something it fails with:

```
Error in event handler for 'undefined': Cannot read property 'selectionText' of undefined TypeError: Cannot read property 'selectionText' of undefined
    at webpg.background.onRequest (chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/background.js:148:46)
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at miscellaneous_bindings:163:26
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:369
chrome.Event.dispatch_ event_bindings:369
chrome.Event.dispatch event_bindings:385
(anonymous function) miscellaneous_bindings:163
chrome.Event.dispatchToListener event_bindings:379
chrome.Event.dispatch_ event_bindings:365
chrome.Event.dispatch event_bindings:385
chromeHidden.Port.dispatchOnMessage miscellaneous_bindings:253
Error in event handler for 'undefined': Cannot read property 'selectionText' of undefined TypeError: Cannot read property 'selectionText' of undefined
    at webpg.background.onRequest (chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/background.js:148:46)
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at miscellaneous_bindings:163:26
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:369
chrome.Event.dispatch_ event_bindings:369
chrome.Event.dispatch event_bindings:385
(anonymous function) miscellaneous_bindings:163
chrome.Event.dispatchToListener event_bindings:379
chrome.Event.dispatch_ event_bindings:365
chrome.Event.dispatch event_bindings:385
chromeHidden.Port.dispatchOnMessage miscellaneous_bindings:253
Error in event handler for 'undefined': Cannot read property 'selectionText' of undefined TypeError: Cannot read property 'selectionText' of undefined
    at webpg.background.onRequest (chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/background.js:148:46)
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at miscellaneous_bindings:163:26
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:369
chrome.Event.dispatch_ event_bindings:369
chrome.Event.dispatch event_bindings:385
(anonymous function) miscellaneous_bindings:163
chrome.Event.dispatchToListener event_bindings:379
chrome.Event.dispatch_ event_bindings:365
chrome.Event.dispatch event_bindings:385
chromeHidden.Port.dispatchOnMessage miscellaneous_bindings:253
Error in event handler for 'undefined': Cannot read property 'selectionText' of undefined TypeError: Cannot read property 'selectionText' of undefined
    at webpg.background.onRequest (chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/background.js:148:46)
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at miscellaneous_bindings:163:26
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:369
chrome.Event.dispatch_ event_bindings:369
chrome.Event.dispatch event_bindings:385
(anonymous function) miscellaneous_bindings:163
chrome.Event.dispatchToListener event_bindings:379
chrome.Event.dispatch_ event_bindings:365
chrome.Event.dispatch event_bindings:385
chromeHidden.Port.dispatchOnMessage miscellaneous_bindings:253
Error in event handler for 'undefined': Cannot read property 'selectionText' of undefined TypeError: Cannot read property 'selectionText' of undefined
    at webpg.background.onRequest (chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/background.js:148:46)
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at miscellaneous_bindings:163:26
    at chrome.Event.dispatchToListener (event_bindings:379:21)
    at chrome.Event.dispatch_ (event_bindings:365:27)
    at chrome.Event.dispatch (event_bindings:385:17)
    at Object.chromeHidden.Port.dispatchOnMessage (miscellaneous_bindings:253:22) event_bindings:369
chrome.Event.dispatch_ event_bindings:369
chrome.Event.dispatch event_bindings:385
(anonymous function) miscellaneous_bindings:163
chrome.Event.dispatchToListener event_bindings:379
chrome.Event.dispatch_ event_bindings:365
chrome.Event.dispatch event_bindings:385
chromeHidden.Port.dispatchOnMessage
```

And since you mentioned LIBC version here the package version of libc6: 

```
libc6:
  installed: 2.13-36
```

Thanks to you for the effort you are putting in this.

**Comment by kylehuff** [comment]
Okay, I suspect it is your version of libc, the next release will have a version of the NPAPI plugin compiled against libc6 v2.13.

I would like still like to see the output of plugin.webpg_status, just curious what those values look like in this scenario, so I can possibly detect this type of issue and provide some more specific/clear error information to make it easier to track down.

**Comment by giacmir** [comment]
Oh I'm sorry... I omitted to paste the webpg_status output... here it is:

```
Object
GNUPGHOME: ""
OpenPGP: Object
file_name: "/usr/bin/gpg"
req_version: "1.4.0"
version: "1.4.12"
__proto__: Object
edit_status: ""
error: false
gpg_agent_info: "/tmp/gpg-whNfP2/S.gpg-agent:3785:1"
gpgconf_detected: true
gpgme_valid: true
gpgme_version: "1.3.2"
plugin: Object
params: Object
id: "webpgPlugin"
type: "application/x-webpg"
__proto__: Object
path: "/home/giacomo/.config/chromium/Default/Extensions/hhaopbphlojhnmbomffjcbnllcenbnih/0.8.8_0/plugins/Linux_x86_64-gcc/npwebpgPlugin-v0.6.1.so"
source_url: "chrome-extension://hhaopbphlojhnmbomffjcbnllcenbnih/_generated_background_page.html"
version: "0.6.1"
__proto__: Object
__proto__: Object
```

**Comment by kylehuff** [comment]
I just checked the linking of webpg-npapi, and the highest version of libc6 referenced with the 64bit module and it's included objects is GLIBC_2.8 -- perhaps the issue we are seeing on your system is unrelated to the version libc6...

Could you provide me with the output of the following command?

`ldd -v /home/giacomo/.config/chromium/Default/Extensions/hhaopbphlojhnmbomffjcbnllcenbnih/0.8.8_0/plugins/Linux_x86_64-gcc/npwebpgPlugin-v0.6.1.so`

**Comment by giacmir** [comment]
Here it is: 

```
ldd -v /home/giacomo/.config/chromium/Default/Extensions/hhaopbphlojhnmbomffjcbnllcenbnih/0.8.8_0/plugins/Linux_x86_64-gcc/npwebpgPlugin-v0.6.1.so
        linux-vdso.so.1 =>  (0x00007fff38116000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa2979d8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa2977bc000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa2974b4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa297232000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa29701c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa296c91000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa297fa4000)

        Version information:
        /home/giacomo/.config/chromium/Default/Extensions/hhaopbphlojhnmbomffjcbnllcenbnih/0.8.8_0/plugins/Linux_x86_64-gcc/npwebpgPlugin-v0.6.1.so:
                libgcc_s.so.1 (GCC_3.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                libdl.so.2 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libdl.so.2
                libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.8) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.5) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (CXXABI_1.3) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
                libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
        /lib/x86_64-linux-gnu/libdl.so.2:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libpthread.so.0:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /usr/lib/x86_64-linux-gnu/libstdc++.so.6:
                libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                libgcc_s.so.1 (GCC_4.2.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.3) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libgcc_s.so.1 (GCC_3.0) => /lib/x86_64-linux-gnu/libgcc_s.so.1
                libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libm.so.6:
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libgcc_s.so.1:
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

**Comment by kylehuff** [comment]
Okay, I can tell from the output that it is not referencing an version of GLIBC that you do not have. The output would include a line something like the following if it did: "libc.so.6 (GLIBC_2.15) => not found"

I will be making a new release with some major changes (hopefully today). We will have to see if any of those changes addresses your issue(s) or at least helps us definitively identify the cause.

**Comment by giacmir** [comment]
I tested the new version (0.9.0) and the situation is the following:

At restart got 3 new windows: two blank and one with two tabs. Each tab has the same error message: 

```
Error Details
Error in Method: undefined
Error Code: -1
Error String: WebPG Plugin failed to load
File: webpgPluginAPI.cpp
Line: -1
System Information
Platform: Linux x86_64
App Version: 5.0 (X11)
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:16.0) Gecko/20100101 Firefox/16.0
Product: Gecko
Sub-product: 20100101
Vendor:
Language: it-IT
```

Webpg menu entries in "tools" are completely unresponsive.
Clicking on any menu entry gives this on the console:

```
Data e ora: 13/11/2012 09:23:41
Errore: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMJSWindow.open]
File sorgente: chrome://webpg-firefox/content/utils.js
Riga: 308
```

and

```
my plugin returned: undefined; version undefined 
[background.js:34]
[load@background.js:513]
```

**Comment by kylehuff** [comment]
Okay, I'm running out of ideas.

I am curious about your GnuPG installation, can you provide me with the output from the follow commands please?

`dpkg -l | grep gnupg`

`which gpg`

`file `which gpg``

`file `which gpg-agent``

They are a shot in the dark, but I am determined to find out why this being such a pain on your system.

**Comment by giacmir** [comment]
Here the requested informations:

```
dpkg -l | grep gnupg
ii  gnupg                                  1.4.12-6                             amd64        GNU privacy guard - a free PGP replacement
ii  gnupg-agent                            2.0.19-1                             amd64        GNU privacy guard - password agent
ii  gnupg2 
                               2.0.19-1                             amd64        GNU privacy guard - a free PGP replacement (new v2.x)
```

```
which gpg
/usr/bin/gpg
```

```
file `which gpg`
/usr/bin/gpg: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0x8efe7a7afe4bbc93f7cf0c66af2737c516266758, stripped
```

```
file `which gpg-agent`
/usr/bin/gpg-agent: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=0x59b7eaf1309ff9435a047a6652a7d9d282fa6f1a, stripped
```

**Comment by kylehuff** [comment]
I have not forgotten about this issue -- but I am still at a loss as to why it occurs.

Stab in the dark, but, are you using IPv6 by chance? Also, have you had any change with the latest version of webpg-firefox? (v0.9.2)

The link to the v0.9.2 is: https://addons.mozilla.org/en-US/firefox/addon/webpg-firefox/versions/

**Comment by giacmir** [comment]
I'm not using ipv6. tried 0.9.2 but it still doesn't works. 

Error messages: 

```
Error Details
Error in Method: undefined
Error Code: -1
Error String: WebPG Plugin failed to load
File: webpgPluginAPI.cpp
Line: -1
System Information
Platform: Linux x86_64
App Version: 5.0 (X11)
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:18.0) Gecko/20100101 Firefox/18.0
Product: Gecko
Sub-product: 20100101
Vendor:
Language: it-IT
```

and

```
There was a problem loading the plugin; the plugin might be incompatibly compiled for this architechture
```

Thanks for the attention.

**Comment by kylehuff** [comment]
Could you try the current release candidate for webpg-firefox? The packaged NPAPI binaries (32bit and 64bit) were compiled using Debian Squeeze, and should work on your system (theoretically).

link to release candidate: http://webpg.org/download/webpg-firefox/webpg-firefox-v0.9.3.xpi

**Comment by giacmir** [comment]
Tried and it doesn't work.
If I go to the settings page there are two messages:

```
There is a problem with your configuration 
```

```
There was a problem loading the plugin; the plugin might be incompatibly compiled for this architechture 
```

in the error console: 

```
Errore: TypeError: webpg.plugin.webpg_status.plugin is undefined
File sorgente: chrome://webpg-firefox/content/about.js
Riga: 97
```

```
Errore: TypeError: webpg.plugin.getPrivateKeyList is not a function
File sorgente: chrome://webpg-firefox/content/key_manager.js
Riga: 488
```

**Comment by kylehuff** [comment]
Just curious if v0.9.4 still gives you issues? link: https://webpg.org/download/webpg-firefox/webpg-firefox-v0.9.4.xpi

**Comment by giacmir** [comment]
Just tested. All seems to work now. Thanks
