### ISSUE TITLE
WebPG Toolbar Icon Not Showing

### ISSUE THREAD

**Issue by willysr** [kylehuff/webpg-firefox#9]
When building from Git, the WebPG toolbar is not showing up
In the preferences, the icon is taken from chrome://webpg-firefox/content/skin/images/examples/toolbar-sample.png, but there are no toolbar-sample.png in the examples directory

the same goes with webPG in the compose menu interface

**Comment by kylehuff** [comment]
I forgot to add the image to the repo - fixed!

**Comment by willysr** [comment]
Thanks
back to testing again
